import { BaseRepository } from './BaseRepository.js';
import Organization from '../models/Organization.js';

export class OrganizationRepository extends BaseRepository {
  constructor() {
    super(Organization);
  }

  /** Find org by slug (auto-generated by slugPlugin) */
  async findBySlug(slug) {
    return Organization.findOne({ slug, deletedAt: null });
  }

  /** Find all orgs created by a user */
  async findByCreator(userId) {
    return Organization.find({ createdBy: userId, deletedAt: null });
  }
}

export default OrganizationRepository;
